
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.proyecto1.compiler.analyzer.javascript;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Let = 18;
  public static final int Require = 31;
  public static final int PuntoComa = 8;
  public static final int Coma = 2;
  public static final int If = 20;
  public static final int BOOLEAN1 = 33;
  public static final int INTEGER = 36;
  public static final int DOUBLE = 34;
  public static final int Clase = 15;
  public static final int Default = 27;
  public static final int Var = 17;
  public static final int ParentesisFinal = 5;
  public static final int LlaveInicio = 6;
  public static final int Else = 21;
  public static final int LlaveFinal = 7;
  public static final int INTEGER1 = 37;
  public static final int OperadorRelacional = 11;
  public static final int Break = 29;
  public static final int OperadorAritmetico = 14;
  public static final int ParentesisInicio = 4;
  public static final int OperadorLogicoNot = 13;
  public static final int STRING1 = 39;
  public static final int While = 24;
  public static final int Consola = 28;
  public static final int For = 22;
  public static final int EOF = 0;
  public static final int BOOLEAN = 32;
  public static final int DosPuntos = 9;
  public static final int OperadorLogico = 12;
  public static final int error = 1;
  public static final int Switch = 25;
  public static final int Funcion = 16;
  public static final int OperadorIdentificador = 10;
  public static final int Break1 = 30;
  public static final int Do = 23;
  public static final int Case = 26;
  public static final int Const = 19;
  public static final int Identificador = 41;
  public static final int STRING = 38;
  public static final int Identificador1 = 40;
  public static final int DOUBLE1 = 35;
  public static final int Igual = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Coma",
  "Igual",
  "ParentesisInicio",
  "ParentesisFinal",
  "LlaveInicio",
  "LlaveFinal",
  "PuntoComa",
  "DosPuntos",
  "OperadorIdentificador",
  "OperadorRelacional",
  "OperadorLogico",
  "OperadorLogicoNot",
  "OperadorAritmetico",
  "Clase",
  "Funcion",
  "Var",
  "Let",
  "Const",
  "If",
  "Else",
  "For",
  "Do",
  "While",
  "Switch",
  "Case",
  "Default",
  "Consola",
  "Break",
  "Break1",
  "Require",
  "BOOLEAN",
  "BOOLEAN1",
  "DOUBLE",
  "DOUBLE1",
  "INTEGER",
  "INTEGER1",
  "STRING",
  "STRING1",
  "Identificador1",
  "Identificador"
  };
}

