
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.proyecto1.compiler.analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GraficaLineas = 22;
  public static final int LlaveInicio = 8;
  public static final int LlaveFinal = 9;
  public static final int ParentesisFinal = 7;
  public static final int ERROR = 30;
  public static final int Identificador = 34;
  public static final int Ruta = 33;
  public static final int Titulo = 24;
  public static final int PuntajeEspecifico = 17;
  public static final int EjeX = 26;
  public static final int Coma = 12;
  public static final int CorcheteInicio = 10;
  public static final int GraficaPie = 21;
  public static final int GenerarReporteEstadistico = 19;
  public static final int STRING = 3;
  public static final int CorcheteFinal = 11;
  public static final int Compare = 23;
  public static final int Cadena = 32;
  public static final int TituloY = 28;
  public static final int PuntajeGeneral = 16;
  public static final int TituloX = 27;
  public static final int EOF = 0;
  public static final int Dollar = 15;
  public static final int GraficaBarras = 20;
  public static final int Decimal = 31;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Archivo = 25;
  public static final int Igual = 5;
  public static final int ParentesisInicio = 6;
  public static final int DefinirGlobales = 18;
  public static final int Valores = 29;
  public static final int PuntoComa = 13;
  public static final int DosPuntos = 14;
  public static final int DOUBLE = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Linea",
  "STRING",
  "DOUBLE",
  "Igual",
  "ParentesisInicio",
  "ParentesisFinal",
  "LlaveInicio",
  "LlaveFinal",
  "CorcheteInicio",
  "CorcheteFinal",
  "Coma",
  "PuntoComa",
  "DosPuntos",
  "Dollar",
  "PuntajeGeneral",
  "PuntajeEspecifico",
  "DefinirGlobales",
  "GenerarReporteEstadistico",
  "GraficaBarras",
  "GraficaPie",
  "GraficaLineas",
  "Compare",
  "Titulo",
  "Archivo",
  "EjeX",
  "TituloX",
  "TituloY",
  "Valores",
  "ERROR",
  "Decimal",
  "Cadena",
  "Ruta",
  "Identificador"
  };
}

